### ISSUE TITLE
Plugin does not show up in Xcode 13.1 (13A1030d)

### ISSUE THREAD

**Issue by lutzmi** [zoejessica/AccessControlKitty#6]
Hi,

neither the App Store version nor the compiled version shows up in the Xcode edit. I am using the SwiftFormat plugin, which shows up, so it does not seem to be a general problem. Both, "The Kitty" ;-) and SwiftFormat show up in the System Preferences -> Extensions. So the plugin is there, but can not be used by Xcode.

Any idea where to look for clues, what the issue is?

Thank you!
- Michael

**Comment by michaello** [comment]
@lutzmi you need to add XcodeKit framework to extension:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/4096232/149574089-2db2638d-979a-4048-ae1c-7a83b57a887f.png">

**Comment by lutzmi** [comment]
@michaello Thanks, that did it! :-)
